---
- name: Config_Cisco
  gather_facts: no
  hosts: all
  connection: network_cli

  tasks:
    - name: Config Loopback
      ios_config:
        parents: "interface Loopback 8"
        lines: 
          - description me hicieron con ansible tambien
          - ip address 8.8.8.8 255.255.255.255
    - name: Config 
