---
- name: Playbook de Prueba
  gather_facts: false
  hosts: all
  vars:
    ansible_become: yes
    ansible_become_method: sudo
    ansible_user: "{{ server_username  }}"
    ansible_ssh_pass: "{{ server_password  }}"
    ansible_become_pass: "{{ server_password  }}"

  tasks:
    - name: Ping
      ping:

